project/config/urls.py
from django.contrib import admin
from django.urls import path, include

from core.homepage.views import IndexView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('login/', include('core.login.urls')),
    path('erp/', include('core.erp.urls')),
    path('erp/', include('core.product.urls')),
    path('dashboard/', include('core.dashboard.urls')),
    path('test/', include('core.filtros.urls')),
    path('client/', include('core.client.urls')),
    path('sale/', include('core.Sale.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/client/urls.py
from django.urls import path

from core.client.views import *

app_name = 'client'

urlpatterns = [
    path('client/', ClientView.as_view(), name='client_view'),


]

project/core/dashboard/urls.py
from django.urls import path

from core.dashboard.views import DashBoardView

urlpatterns =[
    path('', DashBoardView.as_view(), name='dashboard')
]

project/core/erp/urls.py
from django.urls import path

from core.erp.views import *

app_name = 'category'

urlpatterns = [
    path('category/form/', CategoryFormView.as_view(), name='category_form'),
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

]

project/core/product/urls.py
from django.urls import path
from core.product.views import *

app_name = 'product'

urlpatterns = [
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
]

project/core/dashboard/models.py
from django.db import models

# Create your models here.

project/core/dashboard/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class DashBoardView(TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = "Panel de admin."
        return context

project/templates/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition layout-top-nav">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>Example 3.0</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Layout</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block for js -->
    {% block javascript %}

    {% endblock %}

    <script>
        {% if messages %}
            html =''
            {% for message in messages %}
                html += '{{message}}';
            {% endfor %}
            alert(html)
        {% endif %}
    </script>
    </body>
{% endblock %}

project/templates/dashboard.html
{% extends 'body.html' %}

project/templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

project/templates/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
    <div class="container">
        <a href="#" class="navbar-brand">
            <img src="{% static 'img/logo.png' %}" alt="AdminLTE Logo"
                 class="brand-image"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">Hades</span>
        </a>
        <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse order-3" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="nav-link"><i class="fas fa-home"></i> Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                       class="nav-link dropdown-toggle"><i class="fas fa-folder-open"></i> Mantenimientos</a>
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                        <li><a href="{% url 'category:category_list' %}" class="dropdown-item"><i class="fas fa-truck-loading"></i> Categorías</a></li>
                        <li><a href="{% url 'product:product_list'   %}" class="dropdown-item"><i class="fas fa-boxes"></i> Productos</a></li>
                        <li><a href="{% url 'client:client_view' %}" class="dropdown-item"><i class="fas fa-users"></i> Clientes</a></li>
                        <li><a href="#" class="dropdown-item"><i class="fas fa-shopping-cart"></i> Ventas</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
            <li class="">
                    <a href="{% url 'logout' %}" class="nav-link" >
                        <span class=" badge-warning navbar-badge">LogOut</span>
                    </a>
            </li>
        </ul>
    </div>
</nav>

project/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ title }}</title>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback">
    <script src="https://kit.fontawesome.com/540cb77d47.js" crossorigin="anonymous"></script>
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/AdminLTE-3.2.0/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- JQuery confirm -->
    <link href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/jquery.js' %}"></script>
    <script src="{% static 'lib/AdminLTE-3.2.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/AdminLTE-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/AdminLTE-3.2.0/js/adminlte.min.js' %}"></script>
    <!-- JQuery confirm -->
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}">

        <!-- sweetalert -->
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- Function of js -->
    <script src="{% static 'js/functions.js' %}"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <!-- Block Head-->

    {% block head %}

    {% endblock %}
</head>
{% block body %}

{% endblock %}
</html>

project/templates/index.html
{% extends 'body.html' %}

{% block content %}

{% endblock %}

project/templates/second.html
{% extends 'index.html' %}

{% block content %}

    <a href="{% url 'erp:secondView' %}">Click</a>

    <ul>
        {% for product in products %}
            <li>{{ product.id }} / {{ product.name }} / {{ product.cate.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

project/templates/test.html
{% extends 'body.html' %}
{% load static %}
{% block head %}
    <link href="{% static 'lib/select2-4.1.0-rc.0/dist/css/select2.min.css' %}" rel="stylesheet"/>
    <script src="{% static 'lib/select2-4.1.0-rc.0/dist/js/select2.min.js' %}"></script>
{% endblock %}
{% block content %}
    <form method="post" action="." enctype="multipart/form-data">
        <div class="card-footer">
            <a href="{{ list_url }}" class="btn btn-primary " id="btnTest">
                <i class="fa-solid fa-backward"></i>
                Atras
            </a>
        </div>
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label>Categorias: </label>
                    {{ form.categorias }}
                </div>
                <div class="form-group">
                    <label>Productos: </label>
                    {{ form.productos }}
                </div>
            </div>


        </div>
    </form>
    <script>

        let select_product = $('select[name="productos"]');
        $(function () {
            $('.select2').select2({});
            $('select[name="categorias"]').on('change', function () {
                let id = $(this).val();

                let option = '<option value="">-----------------</option>';
                $.ajax({
                    url: window.location.pathname,
                    type: 'POST',
                    data: {
                        'action': 'search_product_id',
                        'id': id,
                    },
                    dataType: 'json',
                }).done(function (data) {
                    console.log(data)
                    if (!data.hasOwnProperty('error')) {
                        select_product.html('').select2({
                            data: data
                        });
                        /*$.each(data, function (key, value) {
                            option += '<option value="' + value.id + '">' + value.name + '</option>'
                        })*/

                        return false
                    }
                    message_error(data.error);
                }).fail(function (jqXHR, textStatus, errorThrown) {
                    alert(textStatus + " " + errorThrown);
                }).always(function (data) {
                    //select_product.html(option)
                })
            })

        })


    </script>
{% endblock %}