project/config/urls.py
from django.contrib import admin
from django.urls import path, include

from core.homepage.views import IndexView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('login/', include('core.login.urls')),
    path('erp/', include('core.erp.urls')),
    path('erp/', include('core.product.urls')),
    path('dashboard/', include('core.dashboard.urls')),
    path('test/', include('core.filtros.urls')),
    path('client/', include('core.client.urls')),
    path('sale/', include('core.Sale.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/product/urls.py
from django.urls import path
from core.product.views import *

app_name = 'product'

urlpatterns = [
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
]

project/templates/product/list.html
{% extends 'generic/list.html' %}
{% block column %}
    <tr>
        <th scope="col">Nro.</th>
        <th scope="col">Nombre</th>
        <th scope="col">Imagenes</th>
        <th scope="col">Opciones</th>
    </tr>
{% endblock %}

{% block row %}
    {% for prod in object_list %}
        <tr>
            <td>{{ prod.id }}</td>
            <td>{{ prod.name }}</td>
            <td><img src="{{ prod.get_imagen}}" class="img-fluid d-block mx-auto" style="width: 50px; height: 50px;"></img></td>
            <td>
                <a href="{%  url 'product:product_update' prod.id %}" class="btn btn-warning">
                    <i class="fa-solid fa-file"></i>
                    Update
                </a>
                 <a href="{%  url 'product:product_delete' prod.id %}" class="btn btn-danger">
                    <i class="fa-solid fa-trash"></i>
                    Delete
                </a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

{% block button_create %}
    <a href="{% url 'product:product_create' %}">
        <button class="btn btn-primary " id="btnTest">
            <i class="fa-solid fa-plus"></i>
            Create product
        </button>
    </a>
{% endblock %}

project/templates/product/update.html
{% extends 'generic/form.html' %}