project/config/urls.py
from django.contrib import admin
from django.urls import path, include

from core.homepage.views import IndexView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('login/', include('core.login.urls')),
    path('erp/', include('core.erp.urls')),
    path('erp/', include('core.product.urls')),
    path('dashboard/', include('core.dashboard.urls')),
    path('test/', include('core.filtros.urls')),
    path('client/', include('core.client.urls')),
    path('sale/', include('core.Sale.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/erp/urls.py
from django.urls import path

from core.erp.views import *

app_name = 'category'

urlpatterns = [
    path('category/form/', CategoryFormView.as_view(), name='category_form'),
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

]

project/templates/category/create.html
{% extends 'generic/form.html' %}

{% block list %}
    <div class="card-footer">
        <button type="submit" class="btn btn-primary " id="btnTest">
            <i class="fa-solid fa-floppy-disk"></i>
            Create category
        </button>
    </div>
{% endblock %}

project/templates/category/delete.html
{% extends 'generic/delete.html' %}
{% block blockNavegator %}
{% endblock %}
{% block list %}
    <div class="card-footer">
        <button type="submit" class="btn btn-primary " id="btnTest">
            <i class="fa-solid fa-trash"></i>
            Aceptar
        </button>
    </div>
{% endblock %}

project/templates/category/list.html
{% extends 'generic/list.html' %}
{% block column %}
    <tr>
        <th scope="col">Nro.</th>
        <th scope="col">Nombre</th>
        <th scope="col">Opciones</th>
    </tr>
{% endblock %}

{% block row %}
    {% for cat in object_list %}
        <tr>
            <td>{{ cat.id }}</td>
            <td>{{ cat.name }}</td>
            <td>
                <a href="{%  url 'category:category_update' cat.id %}" class="btn btn-warning">
                    <i class="fa-solid fa-file"></i>
                    Update
                </a>
                 <a href="{%  url 'category:category_delete' cat.id %}" class="btn btn-danger">
                    <i class="fa-solid fa-trash"></i>
                    Delete
                </a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

{% block buttons %}
    <a href="{% url 'category:category_create' %}">
        <button class="btn btn-primary " id="btnTest">
            <i class="fa-solid fa-plus"></i>
            Create category
        </button>
    </a>
{% endblock %}

project/templates/category/update.html
{% extends 'generic/form.html' %}